# Site Settings
title: Michael Cheer, Brewing Consultant
description: Michael Cheer, Brewing Consultant
url: "https://mikecheer.github.io"
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
gems:
  - jekyll-redirect-from
  - jekyll-seo-tag
