# Site Settings
title: Michael Cheer, Brewing Consultant
url: "http://localhost:4000"
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
gems:
  - jekyll-redirect-from
  - jekyll-seo-tag
